### ISSUE TITLE
Exposed Security Key.

### ISSUE THREAD

**Issue by MaarifaMaarifa** [abubakari3bugaru/C.O.D-using-Swahili-Model#2]
There is a security key that is supposed to be used in production secrets exposed in the file "AutomatedVerbalAutopsy/AutomatedVerbalAutopsy/.ipynb_checkpoints/settings-checkpoint.py" of this project.

**Comment by abubakari3bugaru** [comment]
Hey @MaarifaMaarifa, I've managed to remove the key from the project and changing it to a new one. Thanks.
